apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-microservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: time-microservice
  template:
    metadata:
      labels:
        app: time-microservice
    spec:
      containers:
      - name: time-microservice
        image: ocsenasbence/myserver:v1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: time-microservice-service
spec:
  selector:
    app: time-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: corteza-env-config
  namespace: default
data:
  TIME_SERVICE_URL: "http://time-microservice-service"